'use client';
import { createContext, useContext, useEffect, useMemo, useState } from 'react';
import type { Locale, PageKey } from '@/types';
export const locales: Locale[] = ['en-US','ja-JP','zh-CN'];
export const localeNames: Record<Locale,string> = {'en-US':'English','ja-JP':'日本語','zh-CN':'简体中文'};
export const t = {
 'en-US': {brand:'Growth Portfolio',tagline:'Record Growth, Not Just Activity.',nav:{dashboard:'Dashboard',timeline:'Growth Timeline',goals:'Goals',portfolio:'Growth Portfolio',reports:'AI Growth Report',share:'Share Growth Card',settings:'Settings'} as Record<PageKey,string>, mainGoal:'Main Goal',remaining:'Remaining',progress:'Progress',todayGrowth:'Today’s Growth',coach:'AI Growth Coach',viewReport:'View report',growthOS:'Growth Operating System',better:'Am I becoming better?',closer:'Am I closer to my goal?',next:'What should I do next?',share:'Share',likes:'likes',comments:'comments',nextAction:'AI next action',lastEvent:'Last growth event',weekly:'Weekly AI Report',actions:'Next 3 Actions',download:'Download card',copy:'Copy image',x:'Share to X',instagram:'Share to Instagram',language:'Language',theme:'Theme',light:'Light',dark:'Dark',profile:'Profile',goalSelect:'Main goal selection',growthScore:'Growth Score',scoreCaption:'from progress, milestones, consistency, and AI wins',streak:'Growth streak',streakCaption:'days of visible becoming',goalProgress:'Goal Progress',timelinePreview:'Growth Timeline Preview',activeGoals:'Active goals',milestones:'Milestones'},
 'ja-JP': {brand:'Growth Portfolio',tagline:'学習記録ではなく、成長を記録する。',nav:{dashboard:'ダッシュボード',timeline:'成長タイムライン',goals:'目標',portfolio:'成長ポートフォリオ',reports:'AI成長レポート',share:'成長カード共有',settings:'設定'} as Record<PageKey,string>, mainGoal:'メイン目標',remaining:'残り',progress:'進捗',todayGrowth:'今日の成長',coach:'AI成長コーチ',viewReport:'レポートを見る',growthOS:'成長OS',better:'私は成長している？',closer:'目標に近づいている？',next:'次に何をする？',share:'共有',likes:'いいね',comments:'コメント',nextAction:'AI次のアクション',lastEvent:'最後の成長イベント',weekly:'週間AIレポート',actions:'次の3アクション',download:'カードを保存',copy:'画像をコピー',x:'Xに共有',instagram:'Instagramに共有',language:'言語',theme:'テーマ',light:'ライト',dark:'ダーク',profile:'プロフィール',goalSelect:'メイン目標選択',growthScore:'成長スコア',scoreCaption:'進捗・達成・継続・AI実行から算出',streak:'成長ストリーク',streakCaption:'見える前進の連続日数',goalProgress:'目標進捗',timelinePreview:'成長タイムラインプレビュー',activeGoals:'有効な目標',milestones:'マイルストーン'},
 'zh-CN': {brand:'Growth Portfolio',tagline:'记录的不只是行动，而是成长。',nav:{dashboard:'仪表盘',timeline:'成长时间线',goals:'目标',portfolio:'成长作品集',reports:'AI成长报告',share:'分享成长卡片',settings:'设置'} as Record<PageKey,string>, mainGoal:'主要目标',remaining:'剩余',progress:'进度',todayGrowth:'今日成长',coach:'AI成长教练',viewReport:'查看报告',growthOS:'成长操作系统',better:'我是否变得更好？',closer:'我是否更接近目标？',next:'下一步该做什么？',share:'分享',likes:'赞',comments:'评论',nextAction:'AI下一步',lastEvent:'最近成长事件',weekly:'每周AI报告',actions:'接下来3步',download:'下载卡片',copy:'复制图片',x:'分享到 X',instagram:'分享到 Instagram',language:'语言',theme:'主题',light:'浅色',dark:'深色',profile:'个人资料',goalSelect:'主要目标选择',growthScore:'成长分',scoreCaption:'来自进展、里程碑、持续性和AI完成项',streak:'成长连续记录',streakCaption:'持续变好的天数',goalProgress:'目标进展',timelinePreview:'成长时间线预览',activeGoals:'进行中的目标',milestones:'里程碑'}
};
const C = createContext<{locale:Locale;setLocale:(l:Locale)=>void;dict:typeof t['en-US']}|null>(null);
export function I18nProvider({children}:{children:React.ReactNode}){const [locale,setLocale]=useState<Locale>('en-US');useEffect(()=>{const saved=localStorage.getItem('gp-locale') as Locale|null;const nav=navigator.language;const detected=locales.find(l=>l===saved)||locales.find(l=>nav.toLowerCase().startsWith(l.slice(0,2).toLowerCase()))||'en-US';setLocale(detected)},[]);const value=useMemo(()=>({locale,setLocale:(l:Locale)=>{localStorage.setItem('gp-locale',l);setLocale(l)},dict:t[locale]}),[locale]);return <C.Provider value={value}>{children}</C.Provider>}
export function useI18n(){const v=useContext(C);if(!v) throw new Error('useI18n must be used within I18nProvider');return v}
