'use client';
import { Bot, CheckCircle2, Flame, Sparkles, Trophy } from 'lucide-react';
import { aiRecommendations, goals, growthScoreBreakdown, hero, timeline, todaySignals } from '@/data/mockData';
import { useI18n } from '@/lib/i18n';
import { MetricCard, ProgressBar } from '@/components/common/MetricCard';
import { Page } from '@/components/common/Page';

const tone={sky:'from-sky-500 to-blue-500',mint:'from-emerald-400 to-mint',violet:'from-violet-500 to-fuchsia-500',amber:'from-amber-400 to-orange-500'};
export function Dashboard(){const {locale,dict}=useI18n();return <Page title={dict.nav.dashboard} kicker={dict.growthOS}><section className="grid gap-4 xl:grid-cols-[1.4fr_.9fr]"><div className="glass rounded-[2rem] p-7"><span className="chip">{dict.todayGrowth}</span><h1 className="mt-5 text-4xl font-black tracking-tight lg:text-6xl">{hero.question[locale]}</h1><p className="mt-4 max-w-2xl text-lg text-slate-600 dark:text-slate-300">{hero.goal[locale]}</p><div className="mt-6 grid gap-3 md:grid-cols-3"><MetricCard label={dict.growthScore} value={`+${hero.growthScore}`} caption={dict.scoreCaption}/><MetricCard label={dict.streak} value={`${hero.streak}d`} caption={dict.streakCaption}/><MetricCard label={dict.progress} value={`${hero.progress}%`} caption={hero.remaining[locale]}/></div><div className="mt-6"><ProgressBar value={hero.progress}/></div></div><GrowthScore/></section><section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{todaySignals.map(s=><article className="glass rounded-[2rem] p-5" key={s.label[locale]}><div className={`mb-4 grid h-12 w-12 place-items-center rounded-2xl bg-gradient-to-br ${tone[s.tone]} text-white`}><Sparkles size={22}/></div><p className="text-sm text-slate-500 dark:text-slate-400">{s.label[locale]}</p><h2 className="mt-2 text-xl font-black">{s.value[locale]}</h2><p className="mt-3 font-bold text-emerald-500">+{s.impact} {dict.growthScore}</p></article>)}</section><section className="grid gap-4 lg:grid-cols-3"><GoalProgress/><AiCoach/><TimelinePreview/></section></Page>}
function GrowthScore(){const {locale,dict}=useI18n();return <div className="glass rounded-[2rem] p-7"><div className="flex items-center gap-3"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-slate-950 text-white dark:bg-white dark:text-slate-950"><Trophy/></div><div><p className="text-sm text-slate-500">{dict.growthScore}</p><h2 className="text-3xl font-black">+{hero.growthScore}</h2></div></div><div className="mt-5 space-y-3">{growthScoreBreakdown.map(b=><div className="rounded-2xl bg-white/70 p-4 dark:bg-white/5" key={b.label[locale]}><div className="flex justify-between font-bold"><span>{b.label[locale]}</span><span>+{b.points}</span></div><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">{b.detail[locale]}</p></div>)}</div></div>}
function GoalProgress(){const {locale,dict}=useI18n();return <div className="glass rounded-[2rem] p-6"><h2 className="flex items-center gap-2 text-xl font-black"><Trophy size={20}/>{dict.goalProgress}</h2><div className="mt-5 space-y-4">{goals.slice(0,3).map(g=><div key={g.category[locale]}><div className="mb-2 flex justify-between text-sm font-bold"><span>{g.name[locale]}</span><span>{g.progress}%</span></div><ProgressBar value={g.progress}/></div>)}</div></div>}
function AiCoach(){const {locale,dict}=useI18n();return <div className="glass rounded-[2rem] p-6"><h2 className="flex items-center gap-2 text-xl font-black"><Bot size={20}/>{dict.coach}</h2><p className="mt-4 text-slate-600 dark:text-slate-300">{hero.coach[locale]}</p><div className="mt-5 space-y-3">{aiRecommendations.map(r=><div className="rounded-2xl bg-slate-50 p-4 dark:bg-slate-800" key={r.title[locale]}><div className="flex gap-2 font-bold">{r.completed&&<CheckCircle2 className="text-emerald-500" size={19}/>}<span>{r.title[locale]}</span><span className="ml-auto text-emerald-500">+{r.impact}</span></div><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">{r.body[locale]}</p></div>)}</div></div>}
function TimelinePreview(){const {locale,dict}=useI18n();return <div className="glass rounded-[2rem] p-6"><h2 className="flex items-center gap-2 text-xl font-black"><Flame size={20}/>{dict.timelinePreview}</h2><div className="mt-5 space-y-4">{timeline.map(e=><div className="border-l-2 border-sky-200 pl-4" key={e.event[locale]}><span className="chip">+{e.score}</span><h3 className="mt-2 font-black">{e.event[locale]}</h3><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">{e.category[locale]}</p></div>)}</div></div>}
